version: "3"
services:
  frontend:
    build: ./client
    container_name: front
    ports:
      - 3000:80
    restart: always
  backend:
    build: ./server
    container_name: back
    ports:
      - 3001:5000
    restart: always
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-data:/data/db         
  
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
    restart: always
networks: 
  default:
    external:
      name: mynetwork
volumes:
  mongo-data:
    driver: local
      

