apiVersion: apps/v1
kind: Deployment
metadata:
 name: front-deployment
 labels:
   app: angular-deployment
spec:
 replicas: 3
 selector:
   matchLabels:
     app: angular-app
 template:
   metadata:
     labels:
       app: angular-app
   spec:
     containers:
     - name: angular-container
       image: ferielfraj/memoriess
       ports:
       - containerPort: 80
